version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: my-redis
    ports:
      - "6379:6379"
      
  websocket:
    build: .
    container_name: probo-ws
    
  server:
    build: .
    container_name: probo-server
    ports:
      - "3001:3001"
    environment:
      - REDIS_URL=redis://my-redis:6379
      - WEBSOCKET_URL=ws://probo-server:3001
    depends_on:
      - redis
    networks:
      - my-network




  engine:
    build: .
    container_name: probo-worker
    environment:
      - SERVER_URL=ws://probo-server:3001
      - REDIS_URL=redis://my-redis:6379
    depends_on:
      - server
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
